// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwwAqDICNUNak4r_36ApQwHCINDaoPvEU',
    appId: '1:621428389139:web:e43f3aa8c1bbefe215d6e6',
    messagingSenderId: '621428389139',
    projectId: 'thiran-f44c1',
    authDomain: 'thiran-f44c1.firebaseapp.com',
    storageBucket: 'thiran-f44c1.appspot.com',
    measurementId: 'G-HZYB54XX51',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfyQ3QKs6fJTfo4ENXhFkWc8FPRiWH83w',
    appId: '1:621428389139:android:da10eb09c4e5677215d6e6',
    messagingSenderId: '621428389139',
    projectId: 'thiran-f44c1',
    storageBucket: 'thiran-f44c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAegzLUSg18c8W-L0Gn4HGtg73K9pT7pSI',
    appId: '1:621428389139:ios:cefa943491e95a4415d6e6',
    messagingSenderId: '621428389139',
    projectId: 'thiran-f44c1',
    storageBucket: 'thiran-f44c1.appspot.com',
    iosBundleId: 'com.srinathdev.t2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAegzLUSg18c8W-L0Gn4HGtg73K9pT7pSI',
    appId: '1:621428389139:ios:935e74dd2fbec78f15d6e6',
    messagingSenderId: '621428389139',
    projectId: 'thiran-f44c1',
    storageBucket: 'thiran-f44c1.appspot.com',
    iosBundleId: 'com.srinathdev.t2.RunnerTests',
  );
}
